name: 'Submit a Signing Request'
author: 'SignPath GmbH'
description: 'Submits signing request to SignPath and downloads the signed artifact'
inputs:
  connector-url:
    description: 'GitHub Actions SignPath connector URL'
    default: 'https://githubactions.connectors.signpath.io'
    required: true
  api-token:
    description: 'SignPath REST API access token. More details: https://about.signpath.io/documentation/build-system-integration#authentication'
    required: true
  organization-id:
    description: 'SignPath organization ID'
    required: true
  project-slug:
    description: 'SignPath project slug'
    required: true
  signing-policy-slug:
    description: 'SignPath signing policy slug'
    required: true
  wait-for-completion-timeout-in-seconds:
    description: 'Maximum time in seconds that the action will wait for the signing request to complete'
    default: "600"
    required: false
  service-unavailable-timeout-in-seconds:
    description: 'Total time in seconds that the action will wait for a single service call to succeed (across several retries)'
    default: "600"
    required: false
  download-signed-artifact-timeout-in-seconds:
    description: 'HTTP timeout when downloading the signed artifact.'
    default: "300"
    required: false
  artifact-configuration-slug:
    description: 'SignPath artifact configuration slug'
    required: true
  github-artifact-name:
    description: 'Name of the Github Actions artifact'
    required: true
  wait-for-completion:
    description: 'If true, the action will wait for the signing request to complete'
    default: "true"
    required: false
  output-artifact-directory:
    description: 'Path where the signed artifact will be saved. If not specified, the task will not download the artifact from SignPath'
    required: false
  github-token:
    description: 'GitHub access token. Is is recommended to use the default token provided by GitHub: secrets.GITHUB_TOKEN'
    required: true
outputs:
  signing-request-id:
    description: 'The ID of the newly created signing request'
  signing-request-web-url:
    description: 'The URL of the signing request in SignPath'
  signpath-api-url:
    description: 'The base API URL of the SignPath API'
  signed-artifact-download-url:
    description: 'The URL of the signed artifact in SignPath'
runs:
  using: 'node20'
  main: 'dist/index.js'