name: Build

on:
 push:
 pull_request:

env:
  TARGET_REPO_OWNER: SignPath
  SUBMIT_SIGNING_REQUEST_TARGET_REPO: github-action-submit-signing-request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4

    - name: install dev dependencies
      run: npm install

    - name: build the actions
      run: npm run build

    - name: sync tag
      if: github.ref_type == 'tag'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PUBLISH_BUILD_GITHUB_TOKEN }}
        script: |
          const branchName = context.payload.base_ref.replace('refs/heads/', '');

          const list = await github.rest.git.listMatchingRefs({
            owner: ${{ env.TARGET_REPO_OWNER }},
            repo: ${{ env.SUBMIT_SIGNING_REQUEST_TARGET_REPO }},
            ref: 'heads/' + branchName
          });
          
          if (list.data.length === 0) {
            console.log('Branch not found in the terget repository');
          }

          await github.rest.git.createRef({
            owner: ${{ env.TARGET_REPO_OWNER }},
            repo: ${{ env.SUBMIT_SIGNING_REQUEST_TARGET_REPO }},
            ref: 'refs/tags/${{ github.ref_name }}',
            sha: list.data[0].object.sha
          })

    - name: pushes build result
      if: github.ref_type == 'branch'
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUBLISH_BUILD_GITHUB_TOKEN }}
      with:
        source-directory: './actions/submit-signing-request/dist'
        destination-github-username: ${{ env.TARGET_REPO_OWNER }}
        destination-repository-name: ${{ env.SUBMIT_SIGNING_REQUEST_TARGET_REPO }}
        user-name: GHA build process
        create-target-branch-if-needed: true
        commit-message: Original commit message - ${{ github.event.head_commit.message }}
        target-branch: ${{ github.ref_name  }}