name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4

    - name: install dev dependencies
      run: npm install

    - name: build the actions
      run: npm run build

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUBLISH_BUILD_GITHUB_TOKEN }}
      with:
        source-directory: './actions/submit-signing-request/dist'
        destination-github-username: 'volbobvol'
        destination-repository-name: 'action-target'
        user-name: GHA build process
        create-target-branch-if-needed: true
        commit-message: ${{ github.event.head_commit.message }}
        target-branch: ${{ steps.extract_branch.outputs.branch }}